In [1]:
import sys, os, glob
import pandas as pd
sys.path.append('../..')
from src import raw_data_path, direcslist

### Specify paths

In [2]:
exclude = ['!',]

path = raw_data_path + '/Imaging/par2_nebd/'
paths = direcslist(path, 1, exclude=exclude)
print(len(paths))

678

### Exclude paths

Excluding any paths that don't have an af_corrected image and an ROI

In [3]:
paths = [p for p in paths if os.path.exists(p + '/af_corrected.tif')]
paths = [p for p in paths if os.path.exists(p + '/ROI_manual.txt')]
print(len(paths))

669

### Exctract data from paths

In [4]:
dates = []
lines = []
conditions = []
embryo_ids = []
for p in paths:
    code = p.strip('/').split('/')[-2]
    dates.append(code.split('_')[0])
    lines.append(code.split('_')[1])
    if len(code.split('_')) == 4:
        conditions.append(code.split('_')[2])
    else:
        conditions.append('wt')
    embryo_ids.append(int(str(os.path.getctime(glob.glob(p + '/*488 SP 535-50*')[0])).replace('.', '')))

In [5]:
print(len(set(embryo_ids)))

669

### Remove duplicates

In [6]:
unique_ids = []
unique_ids_bool = []
for e in embryo_ids:
    if not e in unique_ids:
        unique_ids.append(e)
        unique_ids_bool.append(True)
    else:
        unique_ids_bool.append(False)

In [7]:
paths = [d for d, u in zip(paths, unique_ids_bool) if u]
dates = [d for d, u in zip(dates, unique_ids_bool) if u]
lines = [d for d, u in zip(lines, unique_ids_bool) if u]
conditions = [d for d, u in zip(conditions, unique_ids_bool) if u]
embryo_ids = [d for d, u in zip(embryo_ids, unique_ids_bool) if u]

### Create dataframe

In [8]:
# Create dataframe
df = pd.DataFrame({'Path': paths, 'EmbryoID': embryo_ids, 'Line': lines, 'Date': dates, 'RNAi': conditions})

# Remove prefix from paths
df['Path'] = df['Path'].apply(lambda x: x[len(raw_data_path):])

df

,Path,EmbryoID,Line,Date,RNAi
0,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689934470687,lp637,200129,wt
1,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689929779656,lp637,200129,wt
2,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689924575844,lp637,200129,wt
3,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",1673968992394886,lp637,200129,wt
4,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689927862203,lp637,200129,wt
...,...,...,...,...,...
664,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/04",16739689395098913,nwg496,220907,wt
665,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/05",16739689395539696,nwg496,220907,wt
666,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/06",1673968940076866,nwg496,220907,wt
667,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/07",16739689396879597,nwg496,220907,wt
668,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/08",16739689398384209,nwg496,220907,wt

### Line dataframe

In [9]:
lines_df = pd.read_csv('par2_lines.csv')
lines_df

,Line,Alternative,Neon,C56S,L109R,L50R,GCN4,6HNL,S241A,PRBH3,it71,Single copy
0,n2,NaN,0,0,0,0,0,0,0,0,0,0
1,lp637,nwg325,1,0,0,0,0,0,0,0,0,0
2,lp637bal,nwg325bal,1,0,0,0,0,0,0,0,0,0
3,nwg201,NaN,1,0,0,0,0,0,0,0,1,0
4,nwg240,NaN,1,1,0,0,0,0,0,0,0,0
5,nwg240bal,NaN,1,1,0,0,0,0,0,0,0,1
6,nwg246,NaN,1,1,0,0,0,0,0,0,1,0
7,nwg338,NaN,1,0,1,0,0,0,0,0,0,0
8,nwg338bal,NaN,1,0,1,0,0,0,0,0,0,1
9,nwg351,NaN,1,0,1,1,0,0,0,0,0,0
10,nwg369,NaN,1,0,1,0,0,0,0,0,1,0
11,nwg374,NaN,1,0,0,0,0,0,1,0,0,0
12,nwg376,nwg377,1,0,0,0,1,0,0,0,0,0
13,nwg398,nwg399,1,0,1,0,1,0,0,0,0,0
14,nwg400,NaN,1,0,0,1,0,0,0,0,0,0
15,nwg400bal,NaN,1,0,0,1,0,0,0,0,0,1
16,nwg407,nwg408,1,1,1,0,0,0,0,0,0,0
17,nwg437,NaN,1,0,0,0,1,0,0,0,1,0
18,nwg456,NaN,1,0,1,0,1,0,0,0,1,0
19,nwg465,NaN,1,0,0,0,1,0,1,0,0,0
20,nwg482,nwg481,1,0,0,0,0,1,0,0,0,0
21,nwg489,NaN,1,0,0,0,1,0,0,1,0,0
22,nwg495,NaN,1,0,0,0,0,0,0,1,0,0
23,nwg496,NaN,1,0,1,0,0,1,0,0,0,0
24,nwg497,NaN,1,0,0,0,0,0,1,1,0,0
25,nwg498,NaN,1,0,0,0,1,0,1,1,0,0
26,nwg381,NaN,1,1,0,0,1,0,0,0,0,0

### Filter embryos not in lines database

In [10]:
for index, row in df.iterrows():
    if not row.Line in list(lines_df.Line.unique()) + list(lines_df.Alternative.unique()):
        df.drop(index, inplace=True)
df.reset_index(inplace=True, drop=True)

In [11]:
df

,Path,EmbryoID,Line,Date,RNAi
0,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689934470687,lp637,200129,wt
1,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689929779656,lp637,200129,wt
2,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689924575844,lp637,200129,wt
3,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",1673968992394886,lp637,200129,wt
4,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689927862203,lp637,200129,wt
...,...,...,...,...,...
664,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/04",16739689395098913,nwg496,220907,wt
665,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/05",16739689395539696,nwg496,220907,wt
666,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/06",1673968940076866,nwg496,220907,wt
667,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/07",16739689396879597,nwg496,220907,wt
668,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/08",16739689398384209,nwg496,220907,wt

### Replace nwg325 with lp637 (different names for same line)

In [12]:
df = df.replace('nwg325', 'lp637')
df

,Path,EmbryoID,Line,Date,RNAi
0,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689934470687,lp637,200129,wt
1,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689929779656,lp637,200129,wt
2,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689924575844,lp637,200129,wt
3,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",1673968992394886,lp637,200129,wt
4,"/Imaging/par2_nebd/200129_lp637_wt_tom4,15,60/...",16739689927862203,lp637,200129,wt
...,...,...,...,...,...
664,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/04",16739689395098913,nwg496,220907,wt
665,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/05",16739689395539696,nwg496,220907,wt
666,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/06",1673968940076866,nwg496,220907,wt
667,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/07",16739689396879597,nwg496,220907,wt
668,"/Imaging/par2_nebd/220907_nwg496_tom4,15,60/08",16739689398384209,nwg496,220907,wt

### Sort by embryo ID

In [13]:
df = df.sort_values(by='EmbryoID')
df.reset_index(inplace=True, drop=True)
df

,Path,EmbryoID,Line,Date,RNAi
0,/Imaging/par2_nebd/200131_nwg201_2001310930par...,16739689889946,nwg201,200131,2001310930par2
1,/Imaging/par2_nebd/220307_n2/N2_3,167396877200836,n2,220307,wt
2,"/Imaging/par2_nebd/210930_nwg407_tom4,15,60/00",167396886153942,nwg407,210930,wt
3,"/Imaging/par2_nebd/211106_nwg407_tom4,15,60/02",167396887925265,nwg407,211106,wt
4,"/Imaging/par2_nebd/220805_lp637_tom4,15,60/03",167396892914197,lp637,220805,wt
...,...,...,...,...,...
664,"/Imaging/par2_nebd/220902_n2_tom4,15,60/18",16739691896146083,n2,220902,wt
665,"/Imaging/par2_nebd/220902_n2_tom4,15,60/17",16739691897957604,n2,220902,wt
666,"/Imaging/par2_nebd/210816_nwg381_tom4,15,60/03",16836230617875345,nwg381,210816,wt
667,"/Imaging/par2_nebd/210816_nwg381_tom4,15,60/04",16836230618681848,nwg381,210816,wt
668,"/Imaging/par2_nebd/210816_nwg381_tom4,15,60/02",16836230618840346,nwg381,210816,wt

### Save

In [14]:
df.to_csv('../../data/par2_nebd_embryos.csv')